export {default as Login} from './screen/Login/Login'
export {default as Register} from './screen/Register/Register'
export {default as Forgotpassword} from './screen/Forgotpassword/Forgotpassword'
export {default as Home} from './screen/Home/Home'
export {default as Profile} from './screen/Profile/Profile'